apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo
spec:
  hosts:
    - "demo"
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: demo
            subset: v2
            port:
              number: 9010
