apiVersion: v1
kind: Namespace
metadata:
  name: external
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-configmap
  namespace: external
data:
  squid.conf: |
    http_port 3128

    acl SSL_ports port 443
    acl CONNECT method CONNECT

    http_access deny CONNECT !SSL_ports
    http_access allow localhost manager
    http_access deny manager
    http_access allow all

    coredump_dir /var/spool/squid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: external
spec:
  selector:
    matchLabels: 
      app: squid
  replicas: 1
  template:
    metadata:
      labels:
        app: squid
    spec:
      volumes:
      - name: proxy-config
        configMap:
          name: proxy-configmap
      containers:
      - name: squid
        image: sameersbn/squid:3.5.27
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: proxy-config
          mountPath: /etc/squid
          readOnly: true
